network: {
# MAC address: 00:26:35:00:00:4c
# Note: on PR2, go to http://192.168.1.1/ to check the IP
# tcp_ip: "192.168.0.10",
tcp_ip: "192.168.111.21",
# tcp_ip: "192.168.1.100",
tcp_port: 10001,
udp_ip: "224.0.0.1",
udp_port: 10002,
}

frameRate: 1
integrationTime: 1500
# integrationTime: 500
modulationFrecuency: 20000

filters: {
# mediaFilter: true,
mediaFilter: false,
filterMedianConfig: 1,
averageFilter: false,
filterAverageConfig_Pixels: false,
filterAverageConfig_Iters: 1,
gaussFilter: false,
filterGaussConfig_Pixels: false,
filterGaussConfig_Iters: 1,
slidingAverage: false,
wigglingCompensation: true,
FPPNCompensation: true,
scalingMM: true,
additiveOffset: true,
temperatureCompensation: true,
scalingDistCalibGradient: false,
scalingDistCalibOffset: true,
filterSLAFconfig: 22
}
amplitudeFilter: false
amplitudeThreshold: 0

